### ISSUE TITLE
Potential typo in documentation

### ISSUE THREAD

**Issue by mikefsp** [libyal/libexe#3]
https://github.com/libyal/libexe/blob/main/documentation/Executable%20(EXE)%20file%20format.asciidoc#687-event-definitions

The signature for Event definitions is defined as "EVTN", however, in my files I see it as "EVNT". Is this a typo or it is version-dependent? The major version in my case is 5.

Thanks anyway for the documentation!

**Comment by joachimmetz** [comment]
@mikefsp thx for flagging, I'll have a closer look when time permits

**Comment by mikefsp** [comment]
I checked it with an older CRIM version (3.1) - it's definitely a typo. "EVNT" is correct.
Another obvious typo is also in the same Event definitions -  Array starts at 16 offset, not 12.

**Comment by joachimmetz** [comment]
Confirmed and addressed in https://github.com/libyal/libexe/commit/ced6797aeba9558d91f2632ece10fc8540958736
