### ISSUE TITLE
How do I compile from source?

### ISSUE THREAD

**Issue by zabisc** [libyal/libexe#4]
libuna_utf8_stream.c
fatal  error C1083:  “..\..\libuna\libuna_utf8_stream.c”: No such file or directory
libcdata_list.c
fatal  error C1083: “..\..\libcdata\libcdata_list.c”: No such file or directory
libcdata_list_element.c
fatal  error C1083: “..\..\libcdata\libcdata_list_element.c”: No such file or directory
.........
pls

**Comment by joachimmetz** [comment]
Correct read https://github.com/libyal/libexe/wiki/Building#read-first if you want to build from source.
