### ISSUE TITLE
How to get the size of an EXE file from its header?

### ISSUE THREAD

**Issue by alanccw** [libyal/libexe#5]
Hi,

In your document https://github.com/libyal/libexe/blob/main/documentation/Executable%20(EXE)%20file%20format.asciidoc, it shows the DOS MZ Header contains :

1. Number of bytes in last 512-byte page of executable, assume V1
2. Total number of 512-byte pages in executable, assume V2

So I use V2 * 512 + V1, but the size is much smaller than the actual EXE file size, why?

**Comment by joachimmetz** [comment]
Per document `This document is intended as a working document of the data format specification for the libexe project.`

Can you explain what you are trying to accomplish? If you are trying to read a PE/COFF exe file, you likely want to read the sections.

**Comment by alanccw** [comment]
@joachimmetz 

I want to get the EXE file size based on its header. 

As for sections, do you means sum up all the data size in all sections to get the file size?

**Comment by joachimmetz** [comment]
Why do want the "size of the EXE file", how is that going to help you? A PE/COFF executable can contain arbitrary information, wouldn't be more relevant to know what parts of a PE/COFF are allocated for which purpose and which parts not?

**Comment by joachimmetz** [comment]
No response from original poster, assume question got somewhat answered, closing issue.
